### PR TITLE
Test: Run automata run-doc-post-process on Windows (Do not merge it)

### PR DESCRIPTION
**Pull request by Exarchias**
This PR was created mostly for collaboration and discussion about its content. The idea, is that I ran a test run of automata run-doc-post-process. and while the process is understood, in windows it is another story, and I had to run many things manual.
This PR is created to show the results of what I did, to discuss them, and to investigate possible problems that may arise when running the command from windows OS.

### CODE REVIEW

**Comment by emrgnt-cmplxty** [comment]
I think part of the problem might be that I was mucking around with refactoring the codebase one last time this morning. I wanted to slim down /automata and so the docs and tests were moved outside.

Can you repeat your experiment from main again?

**Comment by Exarchias** [comment]
Of course! Tomorrow I will repeat the process, and this time I will run it in main, just to have the docs. in place. I will take it a bit slower to avoid any mistakes that could force me to re-clone the repository. 
I do enjoy the task of documentation, and if it is ok, I will try to be active around documentation, (it already looks great).
Thank you for your feedback!

**Comment by Exarchias** [comment]
Hi @emrgnt-cmplxty,

I'd like to share some updates regarding my work on Automata. Today, I decided to generate the documentation files in my main branch of the local repository. This way, I can keep the documentation files for future reference.

To get this done, I used the following sequence of commands while being in the Automata root folder:

```
cd docs
python generate_faq.py
sphinx-build -a .  docs
```

As I'm a Windows user, if this was my first time running the system, I would have had to manually install some packages using pip:

```
pip install sphinx
pip install sphinx_panels
pip install sphinx_rtd_dark_mode
```

However, since I've already done this previously, I didn't need to do it this time. But it's worth mentioning that these dependencies aren't currently in the requirements file, which only includes `sphinx-panels` and `sphinx-rtd-dark-mode==1.2.4`. It might be a good idea to update the requirements file to include these additional dependencies.

I'm also wondering if I need to run the commands:

```
cd docs
python generate_faq.py
sphinx-build -a .  docs
```

every time I fetch changes. My assumption is that I should, given that I have to install the program every time I fetch updates. However, it's something I'll seek clarity on.

Starting today, I've decided to start getting involved with documentation tasks and with any Windows compatibility issues.

That's all from me for now. 
Thanks for reading!

**Comment by Exarchias** [comment]
@emrgnt-cmplxty  One more issue. I just noticed that I need to update the gitignore for the contents of docs/docs or to commit, (or discard), the changes. what should I do?

**Comment by Exarchias** [comment]
@emrgnt-cmplxty I've just observed something else worth noting. The dependencies required on my system seem to be different. Specifically, 'sphinx-panels' corresponds to 'sphinx_panels' and 'sphinx-rtd-dark-mode' corresponds to 'sphinx_rtd_dark_mode' on my system. Please take note that these aren't identical.

**Comment by emrgnt-cmplxty** [comment]
> @emrgnt-cmplxty I've just observed something else worth noting. The dependencies required on my system seem to be different. Specifically, 'sphinx-panels' corresponds to 'sphinx_panels' and 'sphinx-rtd-dark-mode' corresponds to 'sphinx_rtd_dark_mode' on my system. Please take note that these aren't identical.

Great catch! Want to try rectifying?

**Comment by Exarchias** [comment]
Sure! I will do an issue for it and I will take care of it. 
One last question. Do you want me to add docs/docs folder into .gitingnore or handle it differently?
I understand that the folder should be in .gitignore but I had to ask you first, (just to be safe).
I will create separate issues for the 2 different topics, just to have everything neatly organized.
Thank you for your feedback!

**Comment by Exarchias** [comment]
Hi everyone,
During the process of finding my way through sphinx-build, I noticed that I was wrong about the output directory as I was running the following commands to generate the documentation.

```
cd docs
python generate_faq.py
sphinx-build -a . docs
```

However, running `sphinx-build -a . docs` doesn't appear to be the correct usage. The last argument in the `sphinx-build` command should specify the output directory where Sphinx should generate the documentation files which is `_build` and not `docs`, Using `_build` is a common practice when using Sphinx:

```
cd docs
python generate_faq.py
sphinx-build -a . _build
```

The `_build` directory is also listed in our .gitignore file, meaning the files generated there won't clutter our git status.

This concludes this PR and my concerns about the output of the generated documents. Tomorrow I will close the PR, in case, further discussion is desired, today.

**Pull request closed without merging**
